apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-poc
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/vedantsharma/self-managed-argo.git
      revision: main
      directories:
      - path: applications/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: istio
      source:
        repoURL: https://github.com/vedantsharma/self-managed-argo.git
        targetRevision: main
        path: '{{path}}'
        helm:
          releaseName: '{{path.basename}}'
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true 
        syncOptions:   
        - CreateNamespace=true
        - ServerSideApply=true 
