apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  name: imgw-sample
spec:
  deployment:
    metadata:
      labels:
        app: imgw-sample
        gateway-name: imgw-sample
        gateway-type: ingress
        istio: imgw-sample
    replicas:
      count: 1
      min: 1
      max: 1
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
  istioControlPlane:
    name: icp-v117x-sample
    namespace: istio
  runAsRoot: true
  service:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9080
    type: LoadBalancer
  type: ingress
