apiVersion: v2
name: vault
type: application
version: 0.0.0
dependencies:
- name: vault-operator
  version: 1.21.2
  repository: "oci://ghcr.io/bank-vaults/helm-charts"
- name: vault-secrets-webhook
  version: 1.20.0
  repository: oci://ghcr.io/bank-vaults/helm-charts
