apiVersion: v1 
kind: Namespace 
metadata: 
  name: vault 
--- 
apiVersion: operators.coreos.com/v1 
kind: OperatorGroup 
metadata: 
  name: operatorgroup 
  namespace: vault 
spec: 
  targetNamespaces: 
  - vault 
--- 
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: vault 
  namespace: vault 
spec: 
  channel: beta 
  name: vault 
  source: operatorhubio-catalog 
  sourceNamespace: olm